name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      env: 
        CGO_ENABLED: 0   
      run: go build -o healthcheck -ldflags="-s -w" -v ./...
    
    - name: UPX GitHub Action
      uses: crazy-max/ghaction-upx@v1
      with:
        # File to compress
        file: healthcheck
        args: --best

    - name: Test
      run: go test -v ./...
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: healthcheck
        # A file, directory or wildcard pattern that describes what to upload
        path: /healthcheck
